### ISSUE TITLE
Constraint isn't registered in unit test environment

### ISSUE THREAD

**Issue by rmorrise** [gpc/grails-cascade-validation#3]
When running a unit test, the cascade constraint isn't registered with grails. To work around this issue, the following code must be added to the setup() method of the test:

```
def setup() {
        ConstrainedProperty.registerNewConstraint(CascadeValidationConstraint.NAME, CascadeValidationConstraint)
    }
```

Ideally, the plugin should automatically register itself in the test environment.

**Comment by sbglasius** [comment]
This is now described in README.md
